# coding=utf-8
import requests
from multiprocessing.dummy import Pool
import json
import re
import sys
reload(sys)
sys.setdefaultencoding('utf-8')


def cat_value(url):
    num = 0
    res = requests.get(url, allow_redirects=False)
    try:
        if res.headers['via']:
            print url, "有via值  :  ", res.headers['via']
            with open("via_value.txt", "a") as f:
                f.write(url + "的via值为:  " + res.headers['via'] + '\n')
        print res.headers['via']
    except Exception as e:
        num += 1
        print url, "没有via值"
        with open("via_value.txt", "a") as f:
            f.write(url + "没有via值" + '\n')



if __name__ == '__main__':
    url_list = ["http://www.000hub.com/sjt",
                "http://www.00today.com/slytg",
                "http://www.217center.com/SocksShoes",
                "http://www.217pro.com/PlayStation",
                "http://www.217today.com/TYY",
                "http://www.77center.com/yixibai",
                "http://www.77today.com/Sports",
                "http://www.aduwq.com/ddgaga",
                "http://www.aebwv.com/sale1",
                "http://www.afgkk.com/sbxl",
                "http://www.ahvbv.com/LYCQGtw",
                "http://www.amfvb.com/shop",
                "http://www.aqihl.com/Style018",
                "http://www.arntg.com/qzzzx",
                "http://www.atdpa.com/nmbsy",
                "http://www.atgrl.com/",
                "http://www.atlhv.com/shou",
                "http://www.aupkh.com/cjs194",
                "http://www.bafqo.com/NewLautem",
                "http://www.bbgto.com/KttMopTH",
                "http://www.bboyl.com/aijiu0",
                "http://www.bchln.com/Umbrella",
                "http://www.belloline.com/tex",
                "http://www.bhykp.com/HKcatcatpi",
                "http://www.blrmp.com/perfume6",
                "http://www.bnclz.com/6setsofhandbags",
                "http://www.bpbby.com/ML-pofa-xzsb",
                "http://www.buspz.com/myshoes",
                "http://www.busterbuy.com/pelliot",
                "http://www.bustercenter.com/lbs",
                "http://www.busterlink.com/warm",
                "http://www.busterstyle.com/xdxt",
                "http://www.buystou.com/glassesTHA",
                "http://www.caeky.com/SilkLightDress",
                "http://www.cbrzx.com/abdd",
                "http://www.cdadn.com/as",
                "http://www.cfamq.com/Dragonshirt",
                "http://www.ckpyf.com/tbamy.php",
                "http://www.clakv.com/lystb",
                "http://www.cmymu.com/hdx",
                "http://www.cmzni.com/bag",
                "http://www.cqaug.com/Sportscamera",
                "http://www.cuiil.com/Carchargingpump",
                "http://www.culcj.com/hudiexie",
                "http://www.currentlystore.com/rober",
                "http://www.cwqmi.com/Socksshoes",
                "http://www.cxtxe.com/jm",
                "http://www.czpko.com/GGJ",
                "http://www.Dandybuy.com/richness",
                "http://www.datfm.com/hdbx",
                "http://www.dbshopweb.com/SAO",
                "http://www.dgxia.com/djj",
                "http://www.dnmse.com/88484",
                "http://www.dohvj.com/ThaiTw",
                "http://www.dptky.com/hdxtg",
                "http://www.dqpae.com/BTW",
                "http://www.drlfk.com/lyq",
                "http://www.dtnzf.com/xbx",
                "http://www.dulsn.com/fjtptg",
                "http://www.dulwd.com/hk",
                "http://www.dvsrj.com/tatu",
                "http://www.easyshoppingspace.com/scrsej",
                "http://www.eavuj.com/Footmask",
                "http://www.ebrvo.com/Mouse",
                "http://www.ebveo.com/cjs163",
                "http://www.edsdt.com/tw",
                "http://www.efbqz.com/NaRuTo56Tw",
                "http://www.efpyk.com/msb",
                "http://www.eihmy.com/kaidtwSpecify",
                "http://www.elaov.com/dakoubTH",
                "http://www.emyqe.com/HeadHk",
                "http://www.esoav.com/narutotw",
                "http://www.eyajm.com/maikefeng1",
                "http://www.eywyo.com/tht",
                "http://www.ezxvi.com/hk",
                "http://www.fdmpp.com/ldfkneb",
                "http://www.ffeko.com/NewDragonwatch",
                "http://www.ffnyj.com/qweasdzxcvfr",
                "http://www.fhiwc.com/tw",
                "http://www.fkeeh.com/kdmc",
                "http://www.fnywr.com/clothes",
                "http://www.freebuyhome.com/baowenb",
                "http://www.fvuqi.com/sucktsb",
                "http://www.fygat.com/TWgry",
                "http://www.fyunq.com/aishopping",
                "http://www.gaqgu.com/hd.tw.php",
                "http://www.getstou.com/ARCTW",
                "http://www.gguls.com/tw",
                "http://www.gnfqa.com/ej",
                "http://www.gnqod.com/kltb",
                "http://www.goodbuynews.com/hair45",
                "http://www.gotobuymart.com/HKBCMFK",
                "http://www.gpogc.com/LED",
                "http://www.gpvnv.com/beikemian",
                "http://www.gwaci.com/snorkeling",
                "http://www.gwmpy.com/num001",
                "http://www.gwyan.com/DA",
                "http://www.gzmup.com/sdkl1",
                "http://www.happybuymart.com/bbag",
                "http://www.hemnk.com/twhair",
                "http://www.hirfn.com/heifa",
                "http://www.hlszg.com/guoTH",
                "http://www.hooqj.com/ddshoes",
                "http://www.hrfvp.com/umbrella",
                "http://www.hwvjs.com/twCR305WD",
                "http://www.hxunz.com/mybluetooth",
                "http://www.iauvv.com/mysportshoes",
                "http://www.ibtdu.com/aijiuqi",
                "http://www.ibvvw.com/OkayamaDanim",
                "http://www.icqmz.com/tw",
                "http://www.idqoi.com/twwhny",
                "http://www.ifashioncenter.com/Mokopoio",
                "http://www.ifeqw.com/mybluetooth",
                "http://www.iirvn.com/ssqlq",
                "http://www.ijxwz.com/XN-kp",
                "http://www.inxux.com/qzmytw",
                "http://www.ioprp.com/lfch",
                "http://www.iwgcr.com/mysherbal",
                "http://www.iwkuo.com/judiewy",
                "http://www.iwqug.com/Canadagoose",
                "http://www.ixfwf.com/hk",
                "http://www.ixnkv.com/XN-SHOE",
                "http://www.ixnns.com/Angel",
                "http://www.izqbs.com/beauty",
                "http://www.izroi.com/tw",
                "http://www.jbiqa.com/XNqlz",
                "http://www.jmbax.com/shoes2",
                "http://www.jmvhx.com/XN-SY",
                "http://www.jpulq.com/TWPY1",
                "http://www.jqdda.com/dajinbiao1",
                "http://www.jqpst.com/mybag",
                "http://www.kcsku.com/ssqp",
                "http://www.kdkbv.com/ring",
                "http://www.kfeuc.com/twwokuyy",
                "http://www.kgbti.com/tw",
                "http://www.khhci.com/0sFamo",
                "http://www.kkdry.com/yuwoieh",
                "http://www.kkgbo.com/lsx1",
                "http://www.kswau.com/twbengedaoju",
                "http://www.ktfree.com/ginave",
                "http://www.kttuc.com/SmartWTH",
                "http://www.kugxa.com/php",
                "http://www.laexh.com/suit",
                "http://www.lbhtt.com/zxc",
                "http://www.lddig.com/maohgu",
                "http://www.legft.com/mlxylx",
                "http://www.lfklr.com/guo",
                "http://www.ligcd.com/xfsb",
                "http://www.lihzh.com/Wonderpatchleg",
                "http://www.ljucv.com/sf",
                "http://www.lndtu.com/hkyirenfang",
                "http://www.locrw.com/Alovelifering",
                "http://www.lqpse.com/ylnbb",
                "http://www.lqqii.com/sg",
                "http://www.lremt.com/php",
                "http://www.lrnns.com/sad",
                "http://www.ltyze.com/SR",
                "http://www.lyjvb.com/fayou",
                "http://www.mesqv.com/gs",
                "http://www.miwfu.com/MaryJaneshoes",
                "http://www.mmajj.com/DownjacketTH",
                "http://www.mmpln.com/mysportsshoes",
                "http://www.msumb.com/rdf",
                "http://www.muucenter.com/Dancerug",
                "http://www.mvbpb.com/twhatjhgu",
                "http://www.mvror.com/sssuuu",
                "http://www.mxwrs.com/hkwatch",
                "http://www.ncmpy.com/Franceclothes",
                "http://www.ndowb.com/hkbang",
                "http://www.nervm.com/myfeiwatch",
                "http://www.nmjmv.com/watch.php",
                "http://www.nmzlj.com/musicbox.php",
                "http://www.npnug.com/sbjz",
                "http://www.nqyal.com/lgsb",
                "http://www.nrerq.com/yzmftw",
                "http://www.ntqmg.com/2017newstyle",
                "http://www.nuhdx.com/",
                "http://www.nvoji.com/Hair",
                "http://www.nxufm.com/pixiu",
                "http://www.odaeb.com/sjb",
                "http://www.oexrs.com/mz",
                "http://www.offaid.com/crazybaby",
                "http://www.ogfhi.com/pray",
                "http://www.ogpma.com/sucktssyd",
                "http://www.okrta.com/Storagecar",
                "http://www.onrbd.com/SAW",
                "http://www.oreei.com/mysports",
                "http://www.otrjg.com/eh",
                "http://www.oucta.com/nf",
                "http://www.ouiey.com/thpixie",
                "http://www.outletstoday.com/nlpxtg",
                "http://www.owfiy.com/twstarnun",
                "http://www.owiby.com/jbjhk",
                "http://www.oxvdj.com/xcjly",
                "http://www.oyqfd.com/hkcwwj",
                "http://www.pbjtx.com/tt868",
                "http://www.pbvcp.com/XN-SP",
                "http://www.pesjj.com/BackpackTH241241",
                "http://www.pfxgj.com/Catty",
                "http://www.pgkvj.com/myfashionshoes",
                "http://www.pkiph.com/tw",
                "http://www.pnbxn.com/abd",
                "http://www.ptaog.com/ColouredMagneticEyelashes",
                "http://www.ptegb.com/qianyintaiguo",
                "http://www.pzbeb.com/hkyirenfang",
                "http://www.qgwyh.com/HKkitty",
                "http://www.qhwje.com/tw123ahq",
                "http://www.qhymu.com/tevise.tw",
                "http://www.qkmyi.com/",
                "http://www.qlxce.com/cxn",
                "http://www.qnlrg.com/Shoeeee",
                "http://www.qnnek.com/aerialvehiclehk",
                "http://www.qpvur.com/ggrzt",
                "http://www.rcegu.com/TGNB5",
                "http://www.rfkei.com/SKTYF",
                "http://www.rkqdl.com/ukelili.php",
                "http://www.rkxlv.com/mltrust010",
                "http://www.rlrxm.com/StarWarsBB8",
                "http://www.rqtyk.com/Increased",
                "http://www.rxcxi.com/",
                "http://www.rzclp.com/sanjiantao",
                "http://www.samln.com/smile",
                "http://www.sbtme.com/sucktpd",
                "http://www.sgpku.com/hanbanydx",
                "http://www.shopingspace.com/nanmianyi",
                "http://www.smctr.com/TOMAALBERY",
                "http://www.sphfo.com/aden",
                "http://www.storepacific.com/nsqb",
                "http://www.stpkl.com/jpwigcora",
                "http://www.syrwl.com/trust04",
                "http://www.szsvd.com/glas",
                "http://www.szwna.com/ioujask",
                "http://www.tduhx.com/bsdb",
                "http://www.temmb.com/kljx",
                "http://www.texll.com/wink",
                "http://www.thtoday.com/THAIJKZTQQY",
                "http://www.tjlvd.com/ditto",
                "http://www.tjlvq.com/SPORT",
                "http://www.tnlpl.com/Tote",
                "http://www.tqmnv.com/watch",
                "http://www.tsvqw.com/hkzumo",
                "http://www.tuqou.com/Jmq",
                "http://www.tvurs.com/handbag",
                "http://www.tybve.com/NARUTOtw103",
                "http://www.tzrss.com/suyanshuangV7",
                "http://www.uahmk.com/sucktch",
                "http://www.ujbou.com/buguangdeng1",
                "http://www.unhpn.com/sgcarmodel",
                "http://www.upxzx.com/rsqzd",
                "http://www.uqfjy.com/Jeepxin.php",
                "http://www.usixf.com/zxc",
                "http://www.uusyk.com/poruy",
                "http://www.uuuushop.com/xs",
                "http://www.uvhsw.com/rblsg",
                "http://www.uvrva.com/llyysjwyj",
                "http://www.uwjvo.com/mlxyayjlg",
                "http://www.uzbeq.com/lnyy",
                "http://www.uzlyx.com/ktjjsyj",
                "http://www.vdlpf.com/yaokongche",
                "http://www.velenicity.com/hugtw",
                "http://www.venwt.com/KHHF",
                "http://www.vfngv.com/WWOOR",
                "http://www.vgnek.com/tw",
                "http://www.vivistuff.com/shape",
                "http://www.vlkgc.com/Guanyin",
                "http://www.vnqda.com/Sweeperrobot",
                "http://www.vpews.com/NARUTO",
                "http://www.vqycj.com/dsw",
                "http://www.vsfuf.com/dshk",
                "http://www.vywxn.com/rich",
                "http://www.watershophome.com/health",
                "http://www.watershopmart.com/health",
                "http://www.weofe.com/cixiuniuzai",
                "http://www.widpb.com/wyj",
                "http://www.wjtwv.com/youjia.my",
                "http://www.wlnan.com/whitelight",
                "http://www.wrzwf.com/chapaid.php",
                "http://www.wvrbu.com/guoju",
                "http://www.xtdvz.com/fxjx",
                "http://www.xucda.com/liu1214",
                "http://www.ybhum.com/lin1",
                "http://www.ydejk.com/EBEarPhone",
                "http://www.ymqvg.com/clothes",
                "http://www.yohwg.com/twre",
                "http://www.yperj.com/twrmg",
                "http://www.ytjlk.com/qidianTH",
                "http://www.ytnih.com/westudio",
                "http://www.zfaqm.com/highshoes",
                "http://www.zjpej.com/khbkgzk",
                "http://www.zldjv.com/2",
                "http://www.zlppv.com/tw",
                "http://www.znuda.com/MFSGG",
                "http://www.zogvn.com/twbaseballet",
                "http://www.zpnvq.com/camera",
                "http://www.zpuur.com/ZZZjingbaoqi",
                "http://www.zrkwp.com/allse",
                "http://www.zrlvc.com/v",
                "http://www.zrpsd.com/Pet",
                "http://www.zznex.com/my55ccup", ]

    # for url in url_list:
        # 创建10个线程的线程池
    pool = Pool(8)
    # map()高阶函数，用来批量处理函数传参
    pool.map(cat_value, url_list)
    # 关闭线程池
    pool.close()
    # 阻塞主线程，等待子线程结束
    pool.join()